apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: test.yaml
spec:
  flows:
    - route:
        from:
          uri: kamelet:timer-source
          steps:
            - log:
                message: 'Received: ${body}'
            - process:
                ref: '#class:MyPrepareProcessor'
            - log:
                message: 'Received: ${body}'
          parameters:
            period: 2000
            message: hello
        id: demo
